###########################################################
# Defines topics services and frames for all modules

### TF frames #############################################
laser_frame: laser
robot_frame: base_link
odometry_frame: odom
offset_frame: offset
map_frame: map

### ROS topics ############################################
map_topic: map
laser_topic: base_scan

### ROS services ##########################################
map_service: static_map
